import { Menu } from "../../components/menu/menu";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";


config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="es" className="dark">
            <body className={`${inter.className}`}>
                <Menu />
                <div className="md:mx-auto p-4 bg-white dark:bg-neutral-950">
                    {children}

                </div>
                <footer className="dark:bg-gray-900 p-4 bg-gray-200 text-slate-950 dark:text-slate-50 ">
                    footer
                </footer>
            </body>
        </html>
    );
}