import { Menu } from "../../components/menu/menu";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface LayoutProps {
    children: React.ReactNode
    params: {
        locale: string
    }
}
export default async function Layout({ children, params: { locale } }: LayoutProps) {
    const messages = await getMessages();
    return (
        <html lang={locale} className="dark">
            <body className={`${inter.className} `}>
                <Menu />
                <div className="md:mx-auto p-4 2xl:pl-60 2xl:pr-60 bg-white dark:bg-neutral-950" style={{ minHeight: '100vh' }}>
                    <NextIntlClientProvider messages={messages}>
                        {children}
                    </NextIntlClientProvider>
                </div>
                <footer className="dark:bg-gray-900 p-4 bg-gray-200 text-slate-950 dark:text-slate-50">
                    footer
                </footer>
            </body>
        </html>
    );
}